services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./tmp:/tmp/tmp
    networks:
      - appnet
    environment:
      - MYSQL_DATABASE=apollo
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MARIADB_ROOT_HOST='%'
    ports:
      - 3307:3306 # Exposing on a different port to avoid conflict with my-workspace

  my-workspace:
    container_name: enf-workspace
    image: my-workspace:latest
    ports:
      - 80:80
      - 443:443
      - 3306:3306  # Be cautious — overlaps with db service's internal port
      - 6379:6379
      - 11211:11211
    env_file: config/.env
    volumes:
      - www:/srv/www/
      - ./.ssh:/root/.ssh
      - ./:/mnt/my-workspace/
    restart: unless-stopped
    privileged: true
    shm_size: '2gb'
    networks:
      - appnet
    depends_on:
      - db

volumes:
  db_data:
  www:

networks:
  appnet: